name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = ""
database_name = ""

[[kv_namespaces]]
binding = "NOTES_KV"
id = ""
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = ""
preview_bucket_name = "notes-files-preview"
